### PR TITLE
Report review

### PR DESCRIPTION
**Pull request by gomezcatalina**
#Activity
@gomezcatalina updated structure/titles/text of the Reproducible Report.

#Why is this important
Needed re-formatting to support future requests from Remi and 

#Additional Context
Related to: issue #78 

- Title and intro section of the *species module* is now in the `NSARP_dist_crit.rmd` @stoyelq: I may need some help to render that intro section as part of the more general *Species module* so the title and intro are rendered independently from the NSAR section.
- I moved supplementary material to the end of the *general intro* section. May want to explore whether those supplementary materials could be rendered, conditional on what the users selects. 
- I included a new title in the human activities section, which is associated to the first Rmarkdown rendered, not the module itself. We may want to revisit that.

#Support requested

- [x] @stoyelq - would you please change the option 'Cumulative Impact Mapping' in the app to 'Structures, loading, and disposal"

### CODE REVIEW

**Comment by gomezcatalina** [comment]
Sweet! Thank you for the updates and for opening a new issue. Thanks for pointing out the spot for updating the app. It used to be in the _ui_, I believe? Please let me know if there may be any other action items required on my end. I really need to do a deep dive into `whiskers` soon :crossed_fingers:

**Comment by stfinnis** [comment]
I've made all the changes that I could in this branch. 
I'm still having a few issues:

- Something is up with the metadata in **whelk_en.rmd**. The contact information shows up as a list, and the Quality tier entry is missing.
- I could not get **sardist_en.Rmd** to render. There is an issue on Line 76. I don't know the best way to fix that.

There are a few Open Data entries that are a bit unclear to me, and I'm not entirely sure what is being mapped. The Open Data abstracts/explanations aren't clear. I didn't have time to bury through the metadata to figure it out-sorry!!. I tried to make things a bit more descriptive, but they could probably still be expanded. Specifically:

- **lobsterEffort_en.Rmd**: I'm unsure what the grid/polygons (black outlines) represent. I think these should be specified in the Figure captions. You also might want to double check that I have a correct description for what "catch weight" refers to in the Figure caption.
- **benthicEffort_en.Rmd**: I don't really understand what "benthic fishing effort" is, or how it was calculated. I just said report users should refer to the two references that explain their calculation.
- **nitroLoad_en.Rmd**: Same thing here, I don't know if my new figure caption is accurate. You might want to double check this.
- **power_en.Rmd**: I forget almost everything from Physics (sorry Quentin!!) so I might just be dumb and you can ignore this. But the "Megawatts" that's being reported... is this a yearly average? Monthly maximum? I think it needs a bit more of an explanation.

Other than that, things look great! Hopefully these edits make things more clear. I won't be offended (and probably won't know) if you ignore them all!

**Comment by stoyelq** [comment]
Great questions! There was a typo in the whelk open data record contact list, I've fixed that now. I think the sardist issue was a missing library, because I could render it no problem.  You can try installing gridExtra and rerendering, if it renders, and your happy with it, feel free to merge the PR.  

Those other sections are all layers for cumulative impact mapping, so they are still in fairly early in the process, we still need a bit more feedback from Grace and Noreen as to what to make them.

**Comment by stfinnis** [comment]
whelks.rmd looks good! There are no spaces in between the semicolons in the spaces, but that probably doesn't matter
image

I still am not able to get sardist to render, even after installing gridExtra. I'm not sure what's going wrong there. It takes quite a long time to try and render but here's what shows up:
image

Merging is also blocked for me! I don't think I'll have time to merge this even if I get privileges. 

PS I think this is maybe my last commit in this group and I couldn't have been more unhelpful. Sorry!!

**Pull request merged**
